<?
$PERM["/"]["G8"]="X";
$PERM["/"]["*"]="R";
$PERM["index.php"]["G5"]="W";
$PERM["index.php"]["G8"]="X";
$PERM["announcement"]["G8"]="X";
$PERM["buyers_personal_account"]["2"]="D";
$PERM["buyers_personal_account"]["3"]="D";
$PERM["buyers_personal_account"]["4"]="D";
$PERM["buyers_personal_account"]["6"]="X";
$PERM["buyers_personal_account"]["7"]="D";
$PERM["buyers_personal_account"]["5"]="D";
$PERM["buyers_personal_account"]["*"]="D";
$PERM["sellers_personal_account"]["2"]="D";
$PERM["sellers_personal_account"]["3"]="D";
$PERM["sellers_personal_account"]["4"]="D";
$PERM["sellers_personal_account"]["6"]="D";
$PERM["sellers_personal_account"]["7"]="X";
$PERM["sellers_personal_account"]["5"]="D";
$PERM["news"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>