<?
$PERM["index.php.php"]["2"]="R";
$PERM["index.php.php"]["3"]="R";
$PERM["index.php.php"]["4"]="R";
$PERM["index.php.php"]["6"]="R";
$PERM["index.php.php"]["7"]="R";
$PERM["index.php.php"]["5"]="R";
$PERM["index.php.php"]["8"]="X";
?>